-- Import clients from accounting export (export-2026-09-05)
-- Run this in the Supabase SQL editor

INSERT INTO clients (name, slug, type, status, health)
VALUES
  ('Iniesta Academy',                     'iniesta-academy',                'marca_esportiva', 'active', 'healthy'),
  ('Sports World Congress',               'sports-world-congress',          'esdeveniment',    'active', 'healthy'),
  ('AMIC',                                'amic',                           'mitja',            'active', 'healthy'),
  ('BIWPA',                               'biwpa',                          'club_esportiu',   'active', 'healthy'),
  ('BCN & NYC Experience',                'bcn-nyc-experience',             'empresa',         'active', 'healthy'),
  ('Ben Mirat i Èmfasi Produccions',      'ben-mirat-emfasi',               'empresa',         'active', 'healthy'),
  ('CA Sports Marketing',                 'ca-sports-marketing',            'marca_esportiva', 'active', 'healthy'),
  ('BM Granollers',                       'bm-granollers',                  'club_esportiu',   'active', 'healthy'),
  ('Club Deportivo Balonmano Ágreda',     'balonmano-agreda',               'club_esportiu',   'active', 'healthy'),
  ('Club Esportiu Handbol Lloret',        'handbol-lloret',                 'club_esportiu',   'active', 'healthy'),
  ('Club Handbol Esplugues',              'handbol-esplugues',              'club_esportiu',   'active', 'healthy'),
  ('Club Handbol Sant Esteve Sesrovires', 'handbol-sant-esteve',            'club_esportiu',   'active', 'healthy'),
  ('Nautivela',                           'nautivela',                      'empresa',         'active', 'healthy'),
  ('Stay Homas',                          'stay-homas',                     'empresa',         'active', 'healthy'),
  ('Agencia Karmina',                     'agencia-karmina',                'empresa',         'active', 'healthy'),
  ('EAT SLEEP CYCLE',                     'eat-sleep-cycle',                'marca_esportiva', 'active', 'healthy'),
  ('El fum dels déus',                    'el-fum-dels-deus',               'empresa',         'active', 'healthy'),
  ('Vadebò',                              'vadebo',                         'empresa',         'active', 'healthy'),
  ('Esports Parra',                       'esports-parra',                  'empresa',         'active', 'healthy'),
  ('Federació Catalana d''Handbol',       'fch-handbol',                    'federacio',       'active', 'healthy'),
  ('FCEDF',                               'fcedf',                          'federacio',       'active', 'healthy'),
  ('Fersix',                              'fersix',                         'empresa',         'active', 'healthy'),
  ('Salming',                             'salming',                        'marca_esportiva', 'active', 'healthy'),
  ('Grup Autovivo',                       'grup-autovivo',                  'empresa',         'active', 'healthy'),
  ('Fundació Dr. Torrent-Farnell',        'fundacio-torrent-farnell',       'empresa',         'active', 'healthy'),
  ('Fundació Universitària Balmes',       'fundacio-universitaria-balmes',  'empresa',         'active', 'healthy'),
  ('Universitat de Vic',                  'universitat-vic',                'empresa',         'active', 'healthy'),
  ('Girona FC',                           'girona-fc',                      'club_esportiu',   'active', 'healthy'),
  ('Halley Records',                      'halley-records',                 'empresa',         'active', 'healthy'),
  ('Iberia Sports Camps',                 'iberia-sports-camps',            'marca_esportiva', 'active', 'healthy'),
  ('INDESCAT',                            'indescat',                       'federacio',       'active', 'healthy'),
  ('Punto Blanco',                        'punto-blanco',                   'marca_esportiva', 'active', 'healthy'),
  ('Peugeot Opel',                        'peugeot-opel',                   'empresa',         'active', 'healthy'),
  ('Johan Cruyff Institute',              'johan-cruyff-institute',         'empresa',         'active', 'healthy'),
  ('KIRODO',                              'kirodo',                         'empresa',         'active', 'healthy'),
  ('La iaia artesana',                    'la-iaia-artesana',               'empresa',         'active', 'healthy'),
  ('LSA Academy',                         'lsa-academy',                    'marca_esportiva', 'active', 'healthy'),
  ('Tot Per l''Esport',                   'tot-per-lesport',                'empresa',         'active', 'healthy'),
  ('NAISE FC',                            'naise-fc',                       'club_esportiu',   'active', 'healthy'),
  ('New Mobility Solutions',              'new-mobility-solutions',         'empresa',         'active', 'healthy'),
  ('Nomad Ball',                          'nomad-ball',                     'club_esportiu',   'active', 'healthy'),
  ('North3',                              'north3',                         'empresa',         'active', 'healthy'),
  ('Novacar BCN',                         'novacar-bcn',                    'empresa',         'active', 'healthy'),
  ('Off Limits',                          'off-limits',                     'empresa',         'active', 'healthy'),
  ('Oliva Motor Tarragona',               'oliva-motor-tarragona',          'empresa',         'active', 'healthy'),
  ('Oliva Motor Girona',                  'oliva-motor-girona',             'empresa',         'active', 'healthy'),
  ('Precableados',                        'precableados',                   'empresa',         'active', 'healthy'),
  ('Doctor Prats',                        'doctor-prats',                   'empresa',         'active', 'healthy'),
  ('QL Sport',                            'ql-sport',                       'marca_esportiva', 'active', 'healthy'),
  ('El Collell',                          'el-collell',                     'empresa',         'active', 'healthy'),
  ('Royalverd',                           'royalverd',                      'empresa',         'active', 'healthy'),
  ('MCR Agency',                          'mcr-agency',                     'empresa',         'active', 'healthy'),
  ('Lloret Cup',                          'lloret-cup',                     'marca_esportiva', 'active', 'healthy'),
  ('Elite Fut Academy',                   'elite-fut-academy',              'marca_esportiva', 'active', 'healthy'),
  ('Sports Business Institute Barcelona', 'sports-business-institute',      'empresa',         'active', 'healthy'),
  ('Movex Lift',                          'movex-lift',                     'empresa',         'active', 'healthy'),
  ('JAC Citroën',                         'jac-citroen',                    'empresa',         'active', 'healthy'),
  ('Tasias',                              'tasias',                         'empresa',         'active', 'healthy'),
  ('GO MOTOR',                            'go-motor',                       'empresa',         'active', 'healthy'),
  ('OMODA JAECOO MG HONDA',              'omoda-jaecoo-mg',                'empresa',         'active', 'healthy'),
  ('Girona Basket Costa Brava',           'girona-basket',                  'club_esportiu',   'active', 'healthy'),
  ('Revista Movicarga',                   'revista-movicarga',              'mitja',            'active', 'healthy'),
  ('Kempa',                               'kempa',                          'marca_esportiva', 'active', 'healthy'),
  ('UFEC',                                'ufec',                           'federacio',       'active', 'healthy'),
  ('UNIQ Sports',                         'uniq-sports',                    'marca_esportiva', 'active', 'healthy'),
  ('Proodos Training Center',             'proodos-training',               'marca_esportiva', 'active', 'healthy'),
  ('Open Barcelona Pickleball',           'open-barcelona-pickleball',      'esdeveniment',    'active', 'healthy'),
  ('Xarxa Audiovisual Local',             'xal',                            'mitja',            'active', 'healthy')
ON CONFLICT (slug) DO NOTHING;
